[package]
name = "pdm-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
socketcan = { version = "3.5.0", features = ["tokio"] }
tokio = { version = "1.45.1", features = ["full"] }
