name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf
          components: rustfmt
      - name: Check format
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: thumbv7em-none-eabihf
          components: clippy
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: std crates
        run: |
          cargo clippy --all-features --locked \
            -p messages \
            -p pdm \
            -p pdm-tool \
            -- -D warnings
      - name: no_std crates
        run: |
          cargo clippy --all-features --locked \
            --target thumbv7em-none-eabihf \
            -p pdm-20 \
            -p pdm-20-bootloader \
            -- -D warnings
